clientager/core/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('clientager.core.views',
    url(r'^$', 'home', name='home'),
)

clientager/manager/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('clientager.manager.views',
    url(r'^$', 'subscribe', name='subscribe'),
    url(r'^(\d+)/$', 'detail', name='detail'),
)

clientager/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^inscricao/', include('clientager.manager.urls', namespace='subscriptions')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('clientager.core.urls', namespace='core')),
]

clientager/core/models.py
from django.db import models

# Create your models here.

clientager/manager/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Subscription(models.Model):
    name = models.CharField(_('nome'), max_length=100)
    cpf = models.CharField(_('CPF'), max_length=11, unique=True)
    email = models.EmailField(_('email'), blank=True)
    phone = models.CharField(_('telefone'), max_length=20, blank=True)
    created_at = models.DateTimeField(_('criado em'), auto_now_add=True)
    paid = models.BooleanField(_('Pago'), default=False)

    class Meta:
        ordering = ['created_at']
        verbose_name = _(u'inscrição')
        verbose_name_plural = _(u'inscrições')

    def __str__(self):
        return self.name

clientager/manager/forms.py
from django import forms
from django.utils.translation import ugettext as _
from django.core.exceptions import ValidationError
from django.core.validators import EMPTY_VALUES
from clientager.manager.models import Subscription

def CPFValidator(value):
    if not value.isdigit():
        raise ValidationError(_(u'CPF deve conter apenas números.'))
    if len(value) != 11:
        raise ValidationError(_(u'CPF deve ter 11 números.'))


class PhoneWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        widgets = (
            forms.TextInput(attrs=attrs),
            forms.TextInput(attrs=attrs))
        super(PhoneWidget, self).__init__(widgets, attrs)

    def decompress(self, value):
        if not value:
            return [None, None]
        return value.split('-')


class PhoneField(forms.MultiValueField):
    widget = PhoneWidget

    def __init__(self, *args, **kwargs):
        fields = (forms.IntegerField(),
                  forms.IntegerField())
        super(PhoneField, self).__init__(fields, *args, **kwargs)

    def compress(self, data_list):
        if not data_list:
            return ''
        if data_list[0] in EMPTY_VALUES:
            raise forms.ValidationError(_(u'DDD inválido'))
        if data_list[1] in EMPTY_VALUES:
            raise forms.ValidationError(_(u'Número inválido.'))
        return '%s-%s' % tuple(data_list)


class SubscriptionForm(forms.ModelForm):
    phone = PhoneField(label=_('Telefone'), required=False)

    class Meta:
        model = Subscription
        exclude = ('paid',)

    def __init__(self, *args, **kwargs):
        super(SubscriptionForm, self).__init__(*args, **kwargs)

        self.fields['cpf'].validators.append(CPFValidator)

    def clean_name(self):
        name = self.cleaned_data['name']
        words = map(lambda w: w.capitalize(), name.split())
        capitalized_name = ' '.join(words)
        return capitalized_name

    def clean(self):
        super(SubscriptionForm, self).clean()

        if not self.cleaned_data.get('email') and \
           not self.cleaned_data.get('phone'):
             raise ValidationError(_(u'Informe seu e-mail ou telefone.'))

        return self.cleaned_data

clientager/core/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'index.html')

clientager/manager/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from clientager.manager.forms import SubscriptionForm
from clientager.manager.models import Subscription

def subscribe(request):
    if request.method == 'POST':
        return create(request)
    else:
        return new(request)


def new(request):
    return render(request, 'manager/subscription_form.html',
                  {'form': SubscriptionForm()})


def create(request):
    form = SubscriptionForm(request.POST)
    if not form.is_valid():
        return render(request, 'manager/subscription_form.html',
              {'form': form})

    obj = form.save()
    return HttpResponseRedirect('/inscricao/%d/' % obj.pk)


def detail(request, pk):
    subscription = get_object_or_404(Subscription, pk=pk)
    return render(request, 'manager/subscription_detail.html',
                  {'subscription': subscription})

clientager/core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Bootstrap, a sleek, intuitive, and powerful mobile first front-end framework for faster and easier web development.">
    <meta name="keywords" content="HTML, CSS, JS, JavaScript, framework, bootstrap, front-end, frontend, web development">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <title>Clientager · The world's most popular mobile-first and responsive front-end framework.</title>
    <link rel="icon" href="/favicon.ico">

    <!-- Bootstrap CSS and Style page -->
    <link rel="stylesheet" href="{% static "css/bootstrap-4.0.0-alpha.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body data-ng-app="app">
    <nav class="navbar navbar-dark bg-inverse">
      <a class="navbar-brand" href="#">Clientager</a>
      <ul class="nav navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
      </ul>
      <form class="form-inline navbar-form pull-right">
        <input class="form-control" type="text" placeholder="Search">
        <button class="btn btn-primary-outline" type="submit">Search</button>
      </form>
    </nav>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
    <footer class="footer">
      <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p class="text-muted">Copyright © 2015 Clientager. All rights reserved.</p>
            </div>
            <div class="col-md-6">
                <p class="text-muted text-right">Powered with batteries included Python & Made with Django</p>
            </div>
        </div>
      </div>
    </footer>
    <!-- jQuery first, then Bootstrap JS. -->
    <script src="{% static "js/jquery-1.11.3.js" %}"></script>
    <script src="{% static "js/bootstrap-4.0.0-alpha.js" %}"></script>
    <script src="{% static "js/angular-1.4.8.js" %}"></script>
    <script src="{% static "js/angular-cookies-1.4.8.js" %}"></script>
    <script src="{% static "js/angular-ui-mask-1.6.1.js" %}"></script>
  	<script src="{% static "app/app.js" %}"></script>
  	<script src="{% static "app/controllers/manager-controller.js" %}"></script>
  </body>
</html>

clientager/core/templates/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="jumbotron">
      <h1 class="display-3">Bem-vindo ao Clientager!</h1>
      <p class="lead">O gerenciador mais sensacional, para ter o maior controle dos seus clientes, você não pode perder esta oportunidade!</p>
      <hr class="m-y-md">
      <p>Para dúvidas e mais informações entre em contato com <a href="">contact.clientager@gmail.com</a></p>
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="{% url 'subscriptions:subscribe' %}" role="button">Acesse já!</a>
      </p>
    </div>
  </div>
{% endblock content %}

clientager/manager/templates/manager/subscription_detail.html
{% extends 'base.html' %}
{% block content %}
    <p>Parabéns {{ subscription.name }},</p>
    <p>sua inscrição foi realizada em
        {{ subscription.created_at|date:"d/m/Y" }}.
    </p>
    <p>Em breve, entraremos em contato pelo
        {% if subscription.phone %}
            telefone {{ subscription.phone }}
        {% else %}
            e-mail {{ subscription.email }}
        {% endif %}
    </p>
{% endblock content %}

clientager/manager/templates/manager/subscription_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="content" data-ng-controller="ManagerController">
  <form action="." method="POST">
      {%  csrf_token %}
      {% if form.non_field_errors %}
      <div class="alert alert-warning alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        {{ form.non_field_errors }}
      </div>
      {% endif %}
      <div class="form-group row">
        <label for="{{ form.name.id_for_label }}" class="col-sm-1 form-control-label">{{ form.name.label }}</label>
        <div class="col-sm-6">
          {% render_field form.name class="form-control" placeholder=form.name.label %}
          {{ form.name.errors }}
        </div>
      </div>
      <div class="form-group row">
        <label for="{{ form.cpf.id_for_label }}" class="col-sm-1 form-control-label">{{ form.cpf.label }}</label>
        <div class="col-sm-4">
          {% render_field form.cpf class="form-control" placeholder=form.cpf.label ng-model="cpf" ui-mask="999.999.999-99" ui-mask-placeholder="" %}
          {{ form.cpf.errors }}
        </div>
      </div>
      <div class="form-group row">
        <label for="{{ form.email.id_for_label }}" class="col-sm-1 form-control-label">{{ form.email.label }}</label>
        <div class="col-sm-5">
          {% render_field form.email class="form-control" placeholder=form.email.label %}
          {{ form.email.errors }}
        </div>
      </div>
      <div class="form-group row">
        <label for="{{ form.phone.id_for_label }}" class="col-sm-1 form-control-label">{{ form.phone.label }}</label>
        <div class="col-sm-3">
          {% render_field form.phone class="form-control" placeholder=form.phone.label %}
          {{ form.phone.errors }}
        </div>
      </div>
      <button type="submit" class="btn btn-primary">Enviar</button>
  </form>
</div>
{% endblock content %}